### ISSUE TITLE
FAIR Principles for Artifacts

### ISSUE THREAD

**Issue by sherbold** [researchart/patterns#8]
I think the [FAIR principles](https://www.force11.org/group/fairgroup/fairprinciples) should at least be mentioned, ideally be put into context of the artifact guidelines. 

FAIR has become a standard term in many disciplines and is also starting to get frequently mentioned by University guidelines and within calls by funding agencies. While FAIR is restricted to data, our artifact definition covers data and should, therefore, cover FAIR. Consequently, FAIR is also mentioned and encouraged in this years [Data Showcase call of the MSR](https://2021.msrconf.org/track/msr-2021-data-showcase). 

If you agree, I could work on a PR, but not immediately (probably not before March, later if daycares stay closed). If this should be included earlier, some else should pick this up.

**Comment by neilernst** [comment]
Sure - what do we mean though when we refer to them? Are we suggesting `compliance with`? MSR for example says submissions must "attend to" FAIR. What does that mean? There's some pretty onerous criteria in FAIR, e.g., "meta(data) are richly described with a plurality of accurate and relevant attributes"... which sounds a bit like an ontology/OWL etc. To me that is too restrictive, since my philosophy might be succinctly described as "something is better than nothing"

**Comment by sherbold** [comment]
Where did you find that? I can't find the statement in [version B1.0](https://www.force11.org/fairprinciples). I found a different statement: 

Facet-I-sem: Metadata takes advantage of shared controlled vocabularies or ontologies, allowing the mapping of metadata fields between disparate resources (regardless of their syntax in each of those repositories)

FAIR compliance is certainly not easy, I also not sure if FAIR compliance is a requirement for badges, or possibly should be a separate criterion. I tend towards the following:

For data, FAIR should is more or less _available+functional_. 

However, I am not sure yet if this is a perfect match, or if one side has major aspect that is missing on the other side.

**Comment by neilernst** [comment]
this preprint might be relevant: https://arxiv.org/abs/2101.10883 

> This document captures the discussion and deliberation of the FAIR for Research Software (FAIR4RS) subgroup that took a fresh look at the applicability of the FAIR Guiding Principles for scientific data management and stewardship for research software. We discuss the vision of research software as ideally reproducible, open, usable, recognized, sustained and robust, and then review both the characteristic and practiced differences of research software and data. This vision and understanding of initial conditions serves as a backdrop for an attempt at translating and interpreting the guiding principles to more fully align with research software. We have found that many of the principles remained relatively intact as written, as long as considerable interpretation was provided. This was particularly the case for the "Findable" and "Accessible" foundational principles. We found that "Interoperability" and "Reusability" are particularly prone to a broad and sometimes opposing set of interpretations as written. We propose two new principles modeled on existing ones, and provide modified guiding text for these principles to help clarify our final interpretation. A series of gaps in translation were captured during this process, and these remain to be addressed. We finish with a consideration of where these translated principles fall short of the vision laid out in the opening.

**Comment by timm** [comment]
![image](https://user-images.githubusercontent.com/29195/107253794-affdee80-6a04-11eb-8546-e03fa431a5e7.png)

I added the links suggested by @neilernst and @sherbold 

apart from that, I'm with @neilernst that some of their requirements are complex

![image](https://user-images.githubusercontent.com/29195/107254020-e5a2d780-6a04-11eb-8358-a841551edbda.png)

please reopen this issue if it needs it
